### PR TITLE
Move from jbuilder to dune.

### PR DESCRIPTION
**Pull request by kc284**
Signed-off-by: Konstantina Chremmou <konstantina.chremmou@citrix.com>

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Hi, there doesn't seem to be any issue tracker here so I'm replying at the end of this PR but could there be a release that would include this change?

**Comment by lindig** [comment]
The HEAD is tagged as v2.0.1 - what do you mean by release?

**Comment by psafont** [comment]
I would guess a "release" is a PR to https://github.com/ocaml/opam-repository

**Comment by lindig** [comment]
The opam file is part of xs-opam:
* https://github.com/xapi-project/xs-opam/blob/master/packages/xs/fd-send-recv.2.0.1/opam
We usually don't publish our packages at the official opam repo. Not sure what to do here - it feels a bit inconsistent to do it just for this package.

**Comment by djs55** [comment]
I find the package in ocaml/opam-repository quite useful, but it is a bit old and needs the `dune`-ification.

Perhaps I could update the package in ocaml/opam-repository? I think I'm down as the maintainer of that one anyway. Perhaps this resolves the inconsistency: you can continue to focus on `xs-opam` exclusively and I'll make PRs to ocaml/opam-repository now and again.

Alternatively we could consider a more formal repo/package split but I doubt that is really necessary-- if you needed to go in a completely different direction (e.g. adding dependencies on other packages in `xs-opam`) I could start maintaining a fork for ocaml/opam-repository? WDYT?

**Pull request merged**
